name: user_task
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # network
  dio: ^4.0.6

  # state management
  flutter_riverpod: ^2.0.2

  # routing
  go_router: ^5.0.5

  # ui
  cached_network_image: ^3.2.2


  #  localizations
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/localization/

  fonts:
    - family: Manrope-Bold
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf

    - family: Manrope-Light
      fonts:
        - asset: assets/fonts/Manrope-Light.ttf

    - family: Manrope-Regular
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf